name: DeathSwap
version: @version@
main: me.elexation.deathswap.DeathSwap
api-version: "1.13"
authors: [ Elexation ]
permissions:
  deathswap.use:
    description: Allows usage of deathswap
commands:
  Sync:
    description: Sends a sync request to a player for them to accept it with /sync accept <player>
  Unsync:
    description: Unsyncs two players
  Deathswap:
    description: Stops/starts deathswap
